// 存放mutations命名常量
export const SET_USER_AUTHORIZE_INFO = "SET_USER_AUTHORIZE_INFO"; // 设置用户登录数据
export const SET_USER_STATE = "SET_USER_STATE"; // 设置用户登录状态
export const EMPTY_USER_INFO = "EMPTY_USER_INFO"; // 清空用户信息
export const SET_ITEM = "SET_ITEM";   // 设置数据
export const ADD = "ADD";   // 添加操作
export const CUT = "CUT";   // 添加数量
export const DELETE_ITEM = "DELETE_ITEM"; // 删除指定类目
export const DELETE_ALL = "DELETE_ALL"; // 删除所有类目
export const SET_LOTTERY_CODE = "SET_LOTTERY_CODE";   // 设置彩票编码
export const ADD_MULTIPLE = "ADD_MULTIPLE";   // 添加倍数
export const CUT_MULTIPLE = "CUT_MULTIPLE";   // 减少倍数
export const UPDATE_SYS_TIME = "UPDATE_SYS_TIME";   // 更新系统时间
export const SET_REPLACE_ISSUE_TIP_STATE = "SET_REPLACE_ISSUE_TIP_STATE"; // 设置换期提示状态状态
export const SET_LOGIN_CODE = "SET_LOGIN_CODE";   // 设置数据
export const SEL_INDEX_OVERLAY = "SEL_INDEX_OVERLAY";
export const SET_FIND_TYPE_INDEX = "SET_FIND_TYPE_INDEX"; // 设置查找类型index
export const ADD_PAGE = "ADD_PAGE";   // 添加操作
export const UPDATE_SUS_PRODUCT_INDEX = "UPDATE_SUS_PRODUCT_INDEX"; // 更新合约产品指数